/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package swing;

/**
 *
 * @author scott
 */
public class Home extends javax.swing.JFrame {

    /** Creates new form Home */
    public Home() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Info_Gathering = new javax.swing.JMenu();
        Enterprise = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Individual = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        Domain_Recon = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        Network_Scanners = new javax.swing.JMenu();
        nmap = new javax.swing.JMenuItem();
        asm = new javax.swing.JMenuItem();
        asnip = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        Honeypot_Detection = new javax.swing.JMenu();
        honeycaught = new javax.swing.JMenuItem();
        sniffingbear = new javax.swing.JMenuItem();
        Vulnerability_Scanners = new javax.swing.JMenu();
        flan = new javax.swing.JMenuItem();
        rapidscan = new javax.swing.JMenuItem();
        yuki = new javax.swing.JMenuItem();
        WebApp_Scanners = new javax.swing.JMenu();
        sitadel = new javax.swing.JMenuItem();
        wafw00f = new javax.swing.JMenuItem();
        aapfinder = new javax.swing.JMenuItem();
        bfac = new javax.swing.JMenuItem();
        Web_Scanners = new javax.swing.JMenu();
        nikto = new javax.swing.JMenuItem();
        blackwidow = new javax.swing.JMenuItem();
        konan = new javax.swing.JMenuItem();
        dirb = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        Exploitation_Tools = new javax.swing.JMenu();
        msexploit = new javax.swing.JMenu();
        active = new javax.swing.JMenuItem();
        ispy = new javax.swing.JMenuItem();
        SMBGhost = new javax.swing.JMenuItem();
        webexploit = new javax.swing.JMenu();
        xshock = new javax.swing.JMenuItem();
        nekobot = new javax.swing.JMenuItem();
        darkstar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        exploitsearch = new javax.swing.JMenu();
        shodan = new javax.swing.JMenuItem();
        findsploit = new javax.swing.JMenuItem();
        FuzzyDander = new javax.swing.JMenu();
        dander = new javax.swing.JMenuItem();
        fuzz = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        results = new javax.swing.JMenu();
        options = new javax.swing.JMenu();
        updafes = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Terminal");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 20));

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Notes");

        textField1.setText("textField1");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        Info_Gathering.setText("Info Gathering");

        Enterprise.setText("Enterprise");

        jMenuItem1.setText("theHarvester");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Enterprise.add(jMenuItem1);

        jMenuItem2.setText("Osmedeus");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Enterprise.add(jMenuItem2);

        jMenuItem3.setText("ReconSpider");
        Enterprise.add(jMenuItem3);

        jMenuItem4.setText("CredNinja");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Enterprise.add(jMenuItem4);

        Info_Gathering.add(Enterprise);

        Individual.setText("Individual");

        jMenuItem5.setText("Seeker");
        Individual.add(jMenuItem5);

        jMenuItem6.setText("Sherlock");
        Individual.add(jMenuItem6);

        jMenuItem7.setText("xRay");
        Individual.add(jMenuItem7);

        jMenuItem19.setText("Maryam");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        Individual.add(jMenuItem19);

        Info_Gathering.add(Individual);

        jMenuBar1.add(Info_Gathering);

        Domain_Recon.setText("Domain Recon");

        jMenuItem8.setText("SayDog");
        jMenuItem8.setToolTipText("");
        jMenuItem8.setActionCommand("saydog");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Domain_Recon.add(jMenuItem8);

        jMenuItem9.setText("DnsTwist");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Domain_Recon.add(jMenuItem9);

        jMenuItem11.setText("Armory");
        Domain_Recon.add(jMenuItem11);

        jMenuBar1.add(Domain_Recon);

        Network_Scanners.setText("Network Scanners");

        nmap.setText("nMap");
        nmap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmapActionPerformed(evt);
            }
        });
        Network_Scanners.add(nmap);

        asm.setText("AttackSurfaceMapper");
        asm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asmActionPerformed(evt);
            }
        });
        Network_Scanners.add(asm);

        asnip.setText("aSnip");
        asnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asnipActionPerformed(evt);
            }
        });
        Network_Scanners.add(asnip);

        jMenuItem20.setText("Wafw00f");
        Network_Scanners.add(jMenuItem20);

        jMenuItem21.setText("Arp-Scan");
        jMenuItem21.setActionCommand("arp-scan");
        Network_Scanners.add(jMenuItem21);

        jMenuBar1.add(Network_Scanners);

        Honeypot_Detection.setText("HoneyPot Detecters");

        honeycaught.setText("HoneyCaught");
        honeycaught.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honeycaughtActionPerformed(evt);
            }
        });
        Honeypot_Detection.add(honeycaught);

        sniffingbear.setText("SniffingBear");
        sniffingbear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sniffingbearActionPerformed(evt);
            }
        });
        Honeypot_Detection.add(sniffingbear);

        jMenuBar1.add(Honeypot_Detection);

        Vulnerability_Scanners.setText("Vulnerability Scanners");

        flan.setText("Flan");
        flan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flanActionPerformed(evt);
            }
        });
        Vulnerability_Scanners.add(flan);

        rapidscan.setText("RapidScan");
        rapidscan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapidscanActionPerformed(evt);
            }
        });
        Vulnerability_Scanners.add(rapidscan);

        yuki.setText("Yuki-Chan");
        yuki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yukiActionPerformed(evt);
            }
        });
        Vulnerability_Scanners.add(yuki);

        jMenuBar1.add(Vulnerability_Scanners);

        WebApp_Scanners.setText("WebApp Scanners");

        sitadel.setText("Sitadel");
        sitadel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitadelActionPerformed(evt);
            }
        });
        WebApp_Scanners.add(sitadel);

        wafw00f.setText("OneFind");
        wafw00f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wafw00fActionPerformed(evt);
            }
        });
        WebApp_Scanners.add(wafw00f);

        aapfinder.setText("AapFinder");
        aapfinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aapfinderActionPerformed(evt);
            }
        });
        WebApp_Scanners.add(aapfinder);

        bfac.setText("BFAC");
        bfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfacActionPerformed(evt);
            }
        });
        WebApp_Scanners.add(bfac);

        jMenuBar1.add(WebApp_Scanners);

        Web_Scanners.setText("Web Scanners");

        nikto.setText("Nikto");
        nikto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niktoActionPerformed(evt);
            }
        });
        Web_Scanners.add(nikto);

        blackwidow.setText("BlackWidow");
        blackwidow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackwidowActionPerformed(evt);
            }
        });
        Web_Scanners.add(blackwidow);

        konan.setText("Zeus");
        konan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konanActionPerformed(evt);
            }
        });
        Web_Scanners.add(konan);

        dirb.setText("Dirb");
        dirb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirbActionPerformed(evt);
            }
        });
        Web_Scanners.add(dirb);

        jMenu1.setText("Wordpress");

        jMenuItem10.setText("WPScan");
        jMenu1.add(jMenuItem10);

        jMenuItem14.setText("WPForce");
        jMenu1.add(jMenuItem14);

        Web_Scanners.add(jMenu1);

        jMenuBar1.add(Web_Scanners);

        Exploitation_Tools.setText("Exploitation Tools");

        msexploit.setText("MS Exploitation");

        active.setText("ActiveReign");
        msexploit.add(active);

        ispy.setText("iSpy");
        msexploit.add(ispy);

        SMBGhost.setText("SMBGhost");
        msexploit.add(SMBGhost);

        Exploitation_Tools.add(msexploit);

        webexploit.setText("Web Exploiters");

        xshock.setText("xShock");
        webexploit.add(xshock);

        nekobot.setText("NekoBot");
        webexploit.add(nekobot);

        darkstar.setText("VulnX");
        webexploit.add(darkstar);

        jMenu2.setText("DDoS");

        jMenuItem15.setText("Dark Star");
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Impulse");
        jMenu2.add(jMenuItem16);

        webexploit.add(jMenu2);

        Exploitation_Tools.add(webexploit);

        exploitsearch.setText("Exploit Searching");

        shodan.setText("ShodanSploit");
        exploitsearch.add(shodan);

        findsploit.setText("SearchSploit");
        exploitsearch.add(findsploit);

        Exploitation_Tools.add(exploitsearch);

        FuzzyDander.setText("FuzzyDander");

        dander.setText("Danderspritz");
        FuzzyDander.add(dander);

        fuzz.setText("FuzzBunch");
        FuzzyDander.add(fuzz);

        Exploitation_Tools.add(FuzzyDander);

        jMenuItem12.setText("BruteDUM");
        Exploitation_Tools.add(jMenuItem12);

        jMenuItem13.setText("TigerShark");
        Exploitation_Tools.add(jMenuItem13);

        jMenuBar1.add(Exploitation_Tools);

        jMenu3.setText("Post Exploitation");

        jMenuItem17.setText("Elevation of Privileges");
        jMenu3.add(jMenuItem17);

        jMenuItem18.setText("PHPSploit");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem22.setText("WinPwn");
        jMenu3.add(jMenuItem22);

        jMenuItem23.setText("CredHarvester");
        jMenu3.add(jMenuItem23);

        jMenuBar1.add(jMenu3);

        results.setText("Results");
        jMenuBar1.add(results);

        options.setText("Options");

        updafes.setText("Check for Updates");
        updafes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updafesActionPerformed(evt);
            }
        });
        options.add(updafes);

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        options.add(close);

        jMenuBar1.add(options);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void nmapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmapActionPerformed

    private void asmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asmActionPerformed

    private void asnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asnipActionPerformed

    private void honeycaughtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honeycaughtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_honeycaughtActionPerformed

    private void sniffingbearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sniffingbearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sniffingbearActionPerformed

    private void flanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flanActionPerformed

    private void rapidscanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapidscanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rapidscanActionPerformed

    private void yukiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yukiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yukiActionPerformed

    private void sitadelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitadelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitadelActionPerformed

    private void wafw00fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wafw00fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wafw00fActionPerformed

    private void aapfinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aapfinderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aapfinderActionPerformed

    private void bfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bfacActionPerformed

    private void niktoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niktoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niktoActionPerformed

    private void blackwidowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackwidowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blackwidowActionPerformed

    private void konanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konanActionPerformed

    private void dirbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirbActionPerformed

    private void updafesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updafesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updafesActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Domain_Recon;
    private javax.swing.JMenu Enterprise;
    private javax.swing.JMenu Exploitation_Tools;
    private javax.swing.JMenu FuzzyDander;
    private javax.swing.JMenu Honeypot_Detection;
    private javax.swing.JMenu Individual;
    private javax.swing.JMenu Info_Gathering;
    private javax.swing.JMenu Network_Scanners;
    private javax.swing.JMenuItem SMBGhost;
    private javax.swing.JMenu Vulnerability_Scanners;
    private javax.swing.JMenu WebApp_Scanners;
    private javax.swing.JMenu Web_Scanners;
    private javax.swing.JMenuItem aapfinder;
    private javax.swing.JMenuItem active;
    private javax.swing.JMenuItem asm;
    private javax.swing.JMenuItem asnip;
    private javax.swing.JMenuItem bfac;
    private javax.swing.JMenuItem blackwidow;
    private javax.swing.JMenuItem close;
    private javax.swing.JMenuItem dander;
    private javax.swing.JMenuItem darkstar;
    private javax.swing.JMenuItem dirb;
    private javax.swing.JMenu exploitsearch;
    private javax.swing.JMenuItem findsploit;
    private javax.swing.JMenuItem flan;
    private javax.swing.JMenuItem fuzz;
    private javax.swing.JMenuItem honeycaught;
    private javax.swing.JMenuItem ispy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem konan;
    private javax.swing.JMenu msexploit;
    private javax.swing.JMenuItem nekobot;
    private javax.swing.JMenuItem nikto;
    private javax.swing.JMenuItem nmap;
    private javax.swing.JMenu options;
    private javax.swing.JMenuItem rapidscan;
    private javax.swing.JMenu results;
    private javax.swing.JMenuItem shodan;
    private javax.swing.JMenuItem sitadel;
    private javax.swing.JMenuItem sniffingbear;
    private java.awt.TextField textField1;
    private javax.swing.JMenuItem updafes;
    private javax.swing.JMenuItem wafw00f;
    private javax.swing.JMenu webexploit;
    private javax.swing.JMenuItem xshock;
    private javax.swing.JMenuItem yuki;
    // End of variables declaration//GEN-END:variables

}
